backend:
  name: github
  repo: AltSandro/altsandro.github.io
  branch: main

media_folder: img
public_folder: /img


collections:
  - name: "Favicon"
  label: "Favicon Data"
  fields:
    - label: "Favicon Entries"
      name: "favicon"
      file: "json/favicon-data.json"
      fields:
        - { label: "'rel' атрибут", name: "rel", widget: "string" }
        - { label: "sizes (опционально)", name: "sizes", widget: "string", required: false }
        - { label: "type (опционально)", name: "type", widget: "string", required: false }
        - { label: "ссылка, где лежит файл", name: "href", widget: "string" }

  - name: "Страницы"
    label: "Код страниц html"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "404"
        name: "404"
        file: "404.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "CSS"
    label: "Код CSS"
    files:
      - label: "Footer CSS"
        name: "footerCss"
        file: "css/footerMod.css"
        fields:
          - { label: "CSS Content", name: "cssContent", widget: "code", language: "css", required: true, hint: "Редактируйте CSS код" }
          - { label: "style", name: "style", widget: "markdown"}     
  
  - name: "HeroButtons"
    label: "HeroButtons (страница 'ОБО МНЕ' )"
    files:
      - label: "Hero buttons data"
        name: "heroButtonsData"
        file: "json/buttons-data.json"
        fields:
          - { label: "heroButtons_In_AboutPage", name: "heroButtons", widget: "list", fields: [
              { label: "1) Cсылка перехода кнопки(URL)", name: "href", widget: "string"},
              { label: "2) Текст кнопки", name: "text", widget: "string" },
              { label: "3) langswrs - обязательная метка для 4го пункта", name: "langswrs", widget: "string", required: false },
              { label: "4) addAttributeTwo то есть фразу надо data-langswitch-item='...' ", name: "addAttributeTwo", widget: "string", required: false }
            ]}

  - name: "Остальные меняемые кнопки"
    label: "Остальные меняемые кнопки"
    files:
      - label: "Остальные меняемые кнопки (кроме HeroButtons)"
        name: "OtheButtonsData"
        file: "json/buttons-data.json"
        fields:
          - { label: "OtheButtonsData", name: "buttons", widget: "list", fields: [
              { label: "1) Cсылка перехода кнопки(URL)", name: "href", widget: "string"},
              { label: "2) Текст кнопки", name: "text", widget: "string" },
              { label: "3) langswrs - обязательная метка для 4го пункта", name: "langswrs", widget: "string", required: false },
              { label: "4) addAttributeTwo то есть фразу надо data-langswitch-item='...' ", name: "addAttributeTwo", widget: "string", required: false }
            ]}    
  
  - name: "Карусель проектов"
    label: "Карусель проектов ( 'Cмотри на AltSandro D.Pro-Web' )"
    files:
      - label: "Main Project Carousel Data"
        name: "mainProjCarouselData"
        file: "json/mainProjCarousel-data.json"
        fields:
          - { label: "Cлайды карусели проектов", name: "slides", widget: "list", fields: [
              { label: "1) URL на изображение слайд проекта", name: "image", widget: "string" },
              { label: "2) Как подписать слайд", name: "caption", widget: "string" },
              { label: "3) Куда перейдем при клике по слайду(URL)", name: "link", widget: "string", required: false },
              { label: "4) alt фотки(если не прогрузится вдруг...)", name: "alt", widget: "string", required: false },
              { label: "5) Эффект матрицы(для онгоинга)", name: "isMatrixEffect", widget: "boolean", required: false },
              { label: "6) Сообщение эффекта матрицы", name: "matrixEffectMessage", widget: "string", required: false },
              { label: "7) Задержка эффекта матрицы(сек), ~1.3 ставить", name: "matrixEffectDelay", widget: "string", required: false },
              { label: "8) langswrs - всегда такое слово если нужно переводить", name: "langswrs", widget: "string", required: false },
              { label: "9) dataLangswitchItem='...' из 'Файл языкового переключения'", name: "dataLangswitchItem", widget: "string", required: false }
            ]}


  


  

  

