backend:
  name: github
  repo: AltSandro/altsandro.github.io
  branch: main

media_folder: img
public_folder: /img

collections:
  - name: "Страницы"
    label: "Страницы"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "Carousel"
    label: "Carousel"
    files:
      - label: "Main Project Carousel Data"
        name: "mainProjCarouselData"
        file: "json/mainProjCarousel-data.json"
        fields:
          - { label: "Slides", name: "slides", widget: "list", fields: [
              { label: "Image URL", name: "image", widget: "string" },
              { label: "Caption", name: "caption", widget: "string" },
              { label: "Link URL", name: "link", widget: "string" },
              { label: "Alt Text", name: "alt", widget: "string" },
              { label: "Matrix Effect", name: "isMatrixEffect", widget: "boolean", required: false },
              { label: "Matrix Effect Message", name: "matrixEffectMessage", widget: "string", required: false },
              { label: "Matrix Effect Delay", name: "matrixEffectDelay", widget: "string", required: false },
              { label: "Langswrs", name: "langswrs", widget: "string", required: false },
              { label: "Data Langswitch Item", name: "dataLangswitchItem", widget: "string", required: false }
            ]}
