backend:
  name: github
  repo: AltSandro/altsandro.github.io
  branch: main

media_folder: img
public_folder: /img


collections:
  - name: "Favicon"
    label: "Favicon"
    files:
      - label: "Favicon"
        name: "favicon"
        file: "json/favicon-data.json"
        fields:
          - { label: "Favicon Elements", name: "favicon", widget: "list", fields: [
              { label: "1) 'rel' атрибут", name: "rel", widget: "string", required: true },
              { label: "2) sizes (опционально)", name: "sizes", widget: "string", required: false },
              { label: "3) type (опционально)", name: "type", widget: "string", required: false },
              { label: "4) ссылка, где лежит файл", name: "href", widget: "string", required: true }
            ]} 
  
  - name: "HeroButtons"
    label: "HeroButtons (страница 'ОБО МНЕ' )"
    files:
      - label: "Hero buttons data"
        name: "heroButtonsData"
        file: "json/buttons-data.json"
        fields:
          - { label: "HeroButtons_elements", name: "heroButtons", widget: "list", fields: [
              { label: "1) Cсылка перехода кнопки(URL)", name: "href", widget: "string"},
              { label: "2) Текст кнопки", name: "text", widget: "string" },
              { label: "3) langswrs - обязательная метка для 4го пункта", name: "langswrs", widget: "string", required: false },
              { label: "4) addAttributeTwo то есть фразу надо data-langswitch-item='...' ", name: "addAttributeTwo", widget: "string", required: false }
            ]}

  - name: "Остальные меняемые кнопки"
    label: "Остальные меняемые кнопки"
    files:
      - label: "Остальные меняемые кнопки (кроме HeroButtons)"
        name: "Other_Buttons_Data"
        file: "json/buttons-data.json"
        fields:
          - { label: "Elements", name: "buttons", widget: "list", fields: [
              { label: "1) Cсылка перехода кнопки(URL)", name: "href", widget: "string"},
              { label: "2) Текст кнопки", name: "text", widget: "string" },
              { label: "3) langswrs - обязательная метка для 4го пункта", name: "langswrs", widget: "string", required: false },
              { label: "4) addAttributeTwo то есть фразу надо data-langswitch-item='...' ", name: "addAttributeTwo", widget: "string", required: false }
            ]}

  - name: "Skills"
    label: "Skills"
    files:
      - label: "Skills data"
        name: "skillsData"
        file: "json/skills-data.json"
        fields:
          - label: "Skills Elements"
            name: "skills"
            widget: "list"
            fields:
              - { label: "1) Порядковый id элемента (_1.._2.._3)", name: "id", widget: "string" }
              - { label: "2) Порядковый circleId круга (внутренний)", name: "circleId", widget: "string" }
              - { label: "3) Источник изображения (imgSrc)", name: "imgSrc", widget: "string" }
              - { label: "4) Описание изображения (alt)", name: "alt", widget: "string" }
              - { label: "5) Подпись скила (имя)", name: "skillName", widget: "string" }
              - { label: "6) Уровень владения (нехватающих градусов до полных 360)", name: "strokePercent", widget: "string" }
              - { label: "7) Ссылка (link)", name: "link", widget: "string" }
              - { label: "8) Порядковый № 'circle_' (circle1..circle2..circle3)", name: "circleClass", widget: "string" }
              - { label: "9) Отладочный/невидимый (debug)", name: "debug", widget: "boolean", required: false }
       
  - name: "Карусель проектов"
    label: "Карусель проектов ( 'Cмотри на AltSandro D.Pro-Web' )"
    files:
      - label: "Main Project Carousel Data"
        name: "mainProjCarouselData"
        file: "json/mainProjCarousel-data.json"
        fields:
          - { label: "Cлайды карусели проектов", name: "slides", widget: "list", fields: [
              { label: "1) URL на изображение слайд проекта", name: "image", widget: "string" },
              { label: "2) Как подписать слайд", name: "caption", widget: "string" },
              { label: "3) Куда перейдем при клике по слайду(URL)", name: "link", widget: "string", required: false },
              { label: "4) alt фотки(если не прогрузится вдруг...)", name: "alt", widget: "string", required: false },
              { label: "5) Эффект матрицы(для онгоинга)", name: "isMatrixEffect", widget: "boolean", required: false },
              { label: "6) Сообщение эффекта матрицы", name: "matrixEffectMessage", widget: "string", required: false },
              { label: "7) Задержка эффекта матрицы(сек), ~1.3 ставить", name: "matrixEffectDelay", widget: "string", required: false },
              { label: "8) langswrs - всегда такое слово если нужно переводить", name: "langswrs", widget: "string", required: false },
              { label: "9) dataLangswitchItem='...' из 'Файл языкового переключения'", name: "dataLangswitchItem", widget: "string", required: false }
            ]}

  - name: "Галерея Scratch проекта"
    label: "Галерея Scratch проекта"
    files:
      - label: "Scratch Project Gallery"
        name: "scratchProjectGallery"
        file: "json/scratchProjectGallery-data.json"
        fields:
          - label: "Изображения Scratch проекта"
            name: "images"
            widget: "list"
            fields:
              - { label: "1) Ссылка на изображение(href), равно src", name: "href", widget: "string" }
              - { label: "2) Источник изображения (src), равно href", name: "src", widget: "string" }
              - { label: "3) Описание изображения (alt)", name: "alt", widget: "string" }
              - { label: "4) Категория('Scratch' всегда)", name: "category", widget: "string" }
              - { label: "5) Название проекта ('LEMONCHELLO Fruit Hunt' всегда)", name: "name", widget: "string" }

  - name: "Локация"
    label: "Локация"
    files:
      - label: "Location"
        name: "location"
        file: "json/loc-data.json"
        fields:
          - label: "Информация о локации"
            name: "locationInfo"
            widget: "object"
            fields:
              - { label: "1) Адрес", name: "linkText", widget: "string" }
              - { label: "2) Локация на карте (URL)", name: "mapSrc", widget: "string" }

  - name: "Cсылки на месседжеры"
    label: "Cсылки на месседжеры"
    files:
      - label: "Social media links"
        name: "Social media links"
        file: "json/pagesNav-data.json"
        fields:
          - { label: "Social media links", name: "socialLinks", widget: "list", fields: [
              { label: "1) Ссылка на меседжер", name: "href", widget: "string" },
              { label: "2) Расположенте на иконку", name: "imgSrc", widget: "string" },
              { label: "3) Описание иконки (alt)", name: "alt", widget: "string" }
            ]}

  - name: "Navbar - ссылки (чисто по сайту)"
    label: "Navbar - ссылки (чисто по сайту)"
    files:
      - label: "Pages Navigation data"
        name: "pages_Navbar_Link_Data"
        file: "json/pagesNav-data.json"
        fields:
          - { label: "Navbar Navigation", name: "navbarNav", widget: "list", fields: [
              { label: "1) Ссылка на страницу сайта", name: "href", widget: "string" },
              { label: "2) Текст ссылки(как будет отображено на сайте)", name: "text", widget: "string" },
              { label: "3) langswrs - всегда такое слово если нужно переводить", name: "langswrs", widget: "string", required: false },
              { label: "4) Дополнительный атрибут", name: "addAttributeTwo", widget: "string", required: false }
            ]}

  - name: "Footer - ссылки (чисто по сайту)"
    label: "Footer - ссылки (чисто по сайту)"
    files:
      - label: "FooterNavigation data"
        name: "footer_pages_link_Data"
        file: "json/pagesNav-data.json"
        fields:
          - { label: "Footer pages Navigation", name: "footerNav", widget: "list", fields: [
              { label: "1) Ссылка на страницу сайта", name: "href", widget: "string" },
              { label: "2) Текст ссылки(как будет отображено на сайте)", name: "text", widget: "string" },
              { label: "3) langswrs - всегда такое слово если нужно переводить", name: "langswrs", widget: "string", required: false },
              { label: "4) dataLangswitchItem='...' из 'Файл языкового переключения", name: "addAttributeTwo", widget: "string", required: false }
            ]}

  - name: "Страницы"
    label: "Код страниц html"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "404"
        name: "404"
        file: "404.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "CSS"
    label: "Код CSS"
    files:
      - label: "Footer CSS"
        name: "footerCss"
        file: "css/footerMod.css"
        fields:
          - { label: "CSS Content", name: "cssContent", widget: "code", language: "css", required: true, hint: "Редактируйте CSS код" }
          - { label: "style", name: "style", widget: "markdown"}     

- name: "LanguageData"
  label: "Language Translations (Переводы)"
  files:
    - label: "English Translations"
      name: "englishTranslations"
      file: "json/lang-data.json"
      fields:
        - label: "Language"
          name: "en"
          widget: "object"
          fields:
            - { label: "1) Title for Homepage", name: "1", widget: "string" }
            - { label: "2) Browser Video Support", name: "2", widget: "string" }
            - { label: "3) Homepage Greeting", name: "3", widget: "string" }
            - { label: "4) Visit Homepage Text", name: "4", widget: "string" }
            - { label: "5) ABOUT", name: "5", widget: "string" }
            - { label: "6) PROJECTS", name: "6", widget: "string" }
            - { label: "7) CONTACTS", name: "7", widget: "string" }
            - { label: "8) My Homepage", name: "8", widget: "string" }
            - { label: "9) About", name: "9", widget: "string" }
            - { label: "10) Projects", name: "10", widget: "string" }
            - { label: "11) Contacts", name: "11", widget: "string" }
            - { label: "12) Welcome to Homepage", name: "12", widget: "string" }
            - { label: "13) About Me", name: "13", widget: "string" }
            - { label: "14) Explore the website", name: "14", widget: "string" }
            - { label: "15) Homepage created using", name: "15", widget: "string" }
            - { label: "16) Living my best life", name: "16", widget: "string" }
            - { label: "17) Quote", name: "17", widget: "string" }
            - { label: "18) Empty field", name: "18", widget: "string" }
            - { label: "19) ABOUT ME Page Title", name: "19", widget: "string" }
            - { label: "20) About Me Section", name: "20", widget: "string" }
            - { label: "21) This is what I do", name: "21", widget: "string" }
            - { label: "22) Brief info", name: "22", widget: "string" }
            - { label: "23) Passion for development", name: "23", widget: "string" }
            - { label: "24) Reach out to me", name: "24", widget: "string" }
            - { label: "25) To Skills", name: "25", widget: "string" }
            - { label: "26) To Projects", name: "26", widget: "string" }
            - { label: "27) To Contacts", name: "27", widget: "string" }
            - { label: "28) My Skills", name: "28", widget: "string" }
            - { label: "29) PROJECT PAGE Title", name: "29", widget: "string" }
            - { label: "30) Welcome to Projects", name: "30", widget: "string" }
            - { label: "31) Project Info", name: "31", widget: "string" }
            - { label: "32) Find Out More", name: "32", widget: "string" }
            - { label: "33) AltSandro Projects", name: "33", widget: "string" }
            - { label: "34) CS50 Homepage", name: "34", widget: "string" }
            - { label: "35) Ongoing Project", name: "35", widget: "string" }
            - { label: "36) LEMONCHELLO", name: "36", widget: "string" }
            - { label: "37) Quick select SVU", name: "37", widget: "string" }
            - { label: "38) Lemonchello Project", name: "38", widget: "string" }
            - { label: "39) Interested?", name: "39", widget: "string" }
            - { label: "40) Play Now!", name: "40", widget: "string" }
            - { label: "41) Play in fullscreen", name: "41", widget: "string" }
            - { label: "42) Contact Page Title", name: "42", widget: "string" }
            - { label: "43) Contact Me", name: "43", widget: "string" }
            - { label: "44) Have Questions?", name: "44", widget: "string" }
            - { label: "45) Fill the form", name: "45", widget: "string" }
            - { label: "46) Enter Your Name", name: "46", widget: "string" }
            - { label: "47) Enter Your Email", name: "47", widget: "string" }
            - { label: "48) Enter Your Message", name: "48", widget: "string" }
            - { label: "49) Submit", name: "49", widget: "string" }
            - { label: "50) I Have Answers", name: "50", widget: "string" }
            - { label: "51) My Address", name: "51", widget: "string" }
            - { label: "52) Kyiv, Ukraine", name: "52", widget: "string" }
            - { label: "53) My Social Networks", name: "53", widget: "string" }
            - { label: "54) My Location", name: "54", widget: "string" }
            - { label: "55) Thank you", name: "55", widget: "string" }
            - { label: "56) Message Sent", name: "56", widget: "string" }
            - { label: "57) Thanks to", name: "57", widget: "string" }
            - { label: "58) For Illustrations", name: "58", widget: "string" }
            - { label: "59) Projects Page", name: "59", widget: "string" }
            - { label: "60) Complete reCAPTCHA", name: "60", widget: "string" }
            - { label: "61) Error Sending", name: "61", widget: "string" }
            - { label: "62) Fill all fields", name: "62", widget: "string" }
            - { label: "63) Valid email required", name: "63", widget: "string" }
            - { label: "64) Message too long", name: "64", widget: "string" }
            - { label: "65) 404 Page Title", name: "65", widget: "string" }
            - { label: "66) Page Not Found", name: "66", widget: "string" }
            - { label: "67) 404", name: "67", widget: "string" }
            - { label: "68) Return to Homepage", name: "68", widget: "string" }
            - { label: "69) Requested Page Not Found", name: "69", widget: "string" }
            - { label: "70) Return to Homepage", name: "70", widget: "string" }


  

  
