backend:
  name: github
  repo: AltSandro/altsandro.github.io
  branch: main

media_folder: img
public_folder: /img

collections:
  - name: "Страницы"
    label: "Страницы"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "Карусель"
    label: "Карусель"
    files:
      - label: "Main Project Carousel Data"
        name: "mainProjCarouselData"
        file: "json/mainProjCarousel-data.json"
        fields:
          - { label: "Слайды", name: "slides", widget: "list", fields: [
              { label: "URL изображения(локально(желательно) или из инета)", name: "image", widget: "string" },
              { label: "Подпись-заголовок(на карусели подпись слайда)", name: "caption", widget: "string" },
              { label: "URL, куда перейдем при клике, если есть коечно она..", name: "link", widget: "string", required: false },
              { label: "alt подпись фотки(если фотка не прогрузится вдруг...)", name: "alt", widget: "string" },
              { label: "Эффект матрицы(если проект будет онгоинг то да - лучше включить)", name: "isMatrixEffect", widget: "boolean", required: false },
              { label: "Сообщение для эффекта матрицы(если его нет оставить пустым)", name: "matrixEffectMessage", widget: "string", required: false },
              { label: "Задержка для эффекта матрицы(сек), обычно цифру 1.3 ставить", name: "matrixEffectDelay", widget: "string", required: false },
              { label: "Языковой переключатель(на базе закладки "Файл языкового переключения")", name: "langswrs", widget: "string", required: false },
              { label: "Элемент переключателя языка(dataLangswitchItem)= цифра из "Файл языкового переключения", name: "dataLangswitchItem", widget: "string", required: false }
            ]}
