backend:
  name: github
  repo: AltSandro/altsandro.github.io
  branch: main

media_folder: img
public_folder: /img

collections:
  - name: "Страницы"
    label: "Страницы"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "Carousel"
    label: "Carousel"
    files:
      - label: "Main Project Carousel Data"
        name: "mainProjCarouselData"
        file: "json/mainProjCarousel-data.json"
        fields:
          - { label: "Carousel Items", name: "items", widget: "list", fields: [
              { label: "Active", name: "active", widget: "boolean" },
              { label: "Image URL", name: "image", widget: "string" },
              { label: "Alt Text", name: "alt", widget: "string" },
              { label: "Link URL", name: "link", widget: "string" },
              { label: "Caption", name: "caption", widget: "string" },
              { label: "Matrix Effect Button", name: "matrix_effect_button", widget: "boolean" },
              { label: "Matrix URL", name: "matrix_url", widget: "string", required: false },
              { label: "Matrix URL Sec Delay", name: "matrix_url_sec_delay", widget: "string", required: false },
              { label: "Matrix Effect Message", name: "matrix_effect_message", widget: "string", required: false }
            ]}

